### ISSUE TITLE
大佬好

### ISSUE THREAD

**Issue by gaosinihaha** [DVKunion/collie_tricker#1]
为什么无法使用centos来启动服务器？求大佬解惑

**Comment by DVKunion** [comment]
具体仓库地址可以贴一下吗？或者把你的.github.yml配置发一下看看？ 
@gaosinihaha

**Comment by DVKunion** [comment]
看了一下你的仓库

centos-latest这个参数不在github actions `runs-on`可选范围内。

详情可以参考官方文档：https://docs.github.com/zh/actions/using-jobs/choosing-the-runner-for-a-job

action支持的镜像有：
<img width="780" alt="image" src="https://user-images.githubusercontent.com/42199853/229016687-491c0e3a-e9e7-47e5-be88-03d1af2bf2a5.png">

**Comment by gaosinihaha** [comment]
您好，感谢回复：

最近拿ubuntu玩了一段时间，怎么也连接不到外网，虽然偶尔能curl到百度，但是很不稳定，可能是有网关之类做了限制，也就没继续搞了

     祝好


DVK ***@***.***>于2023年3月31日 周五11:38写道：
